name: cv
channels:
- defaults
- conda-forge
- pytorch
- fastai
dependencies:
- black>=18.6b4
- bqplot
- cython>=0.29.1
- fastai==1.0.57
- ipykernel>=4.6.1
- ipywebrtc 
- jupyter>=1.0.0
- lxml>=4.3.2
- matplotlib>=3.1.2
- papermill>=0.15.0
- pip>=19.0.3
- pre-commit>=1.14.4
- pytest>=3.6.4
- python==3.6.8
- pytorch>=1.2.0
- pyyaml>=5.1.2
- requests>=2.22.0
- scikit-learn>=0.19.1
- torchvision>=0.3.0
- pip:
  - nvidia-ml-py3
  - nteract-scrapbook
  - azureml-sdk[notebooks,contrib]>=1.0.30
  - git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI

