# 
# To create the conda environment:
# $ conda env create -f environment.yml
# 
# To update the conda environment:
# $ conda env update -f environment.yml
# 
# To register the conda environment in Jupyter:
# $ conda activate cv
# $ python -m ipykernel install --user --name cv
# 
name: cv
channels:
- defaults
- conda-forge
dependencies:
- python==3.6.8
- jupyter>=1.0.0
- pytest>=3.6.4
- pip>=19.0.3
- pip:
  # NOTE: Make sure of syncing dependencies in `setup.py`
  - .
  - black>=18.6b4
  - ipywebrtc
  - pre-commit>=1.14.4
  - lxml>=4.3.2
  - nteract-scrapbook
