# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
#
variables:
- group: AzureMLConfig
- name  : 'test'
  value : 'run_pytest.py'
- name  : 'testfolder'
  value : '../tests/unit/amlexample'
- name  : 'testmarkers'
  value : '"not notebooks and not spark and not gpu"'
- name  : 'junitxml'
  value : 'reports/test-unit.xml'
- name  : 'maxnodes'
  value : 4
- name  : 'reponame'
  value : 'computervision'
- name  : 'branch'
  value : 'TestJob'
- name  : 'clustername'
  value : 'cv-cpu'
- name  : 'vmsize'
  value : 'STANDARD_D3_V2'
- name  : 'dockerproc'
  value : 'cpu'
- name  : 'expname'
  value : 'unit-test-linux-cpu'
- name  : 'condafile'
  value : 'classification/environment.yml'
trigger: none

pr: none
#- staging 
#- master
  
pool:
 vmImage: 'ubuntu-16.04'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'
    addToPath: true
  displayName: 'Use Python 3.6'

- script: | 
   az login --service-principal -u $(spidentity) -p $(spsecret) --tenant $(sptenant)
  displayName: 'Login to Azure'

# - template: env-setup.yml 

- task: Bash@3
  inputs: 
    script: 
      python .ci/submit_azureml_pytest.py --subid $(subscriptionid) --testfolder $(testfolder) --condafile $(condafile) --testmarkers $(testmarkers) --clustername $(clustername) --expname $(expname) --dockerproc $(dockerproc) --junitxml $(junitxml) --reponame $(reponame) --branch $(branch)
  displayName: 'submit_azureml_pytest'

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/test-*.xml'
  inputs:
    testResultsFiles: '**/test-*.xml'
    failTaskOnFailedTests: true
  condition: succeededOrFailed()